apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-integration-deployment
  namespace: advanced-integration-v3-1
  labels:
    app: advanced-integration
    version: "3.1"
    component: integration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: advanced-integration
      version: "3.1"
  template:
    metadata:
      labels:
        app: advanced-integration
        version: "3.1"
        component: integration
    spec:
      containers:
      - name: advanced-integration
        image: advanced-integration-v3.1:latest
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: advanced-integration-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: data
          mountPath: /app/data
      volumes:
      - name: logs
        emptyDir: {}
      - name: data
        emptyDir: {}
      restartPolicy: Always
