apiVersion: v1
kind: Service
metadata:
  name: advanced-security-service
  namespace: advanced-security
  labels:
    app: advanced-security
spec:
  selector:
    app: advanced-security
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: advanced-security-nodeport
  namespace: advanced-security
  labels:
    app: advanced-security
spec:
  selector:
    app: advanced-security
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: NodePort
