apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-automation-deployment
  namespace: advanced-automation-v3-1
  labels:
    app: advanced-automation
    version: "3.1"
    component: automation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: advanced-automation
      version: "3.1"
  template:
    metadata:
      labels:
        app: advanced-automation
        version: "3.1"
        component: automation
    spec:
      containers:
      - name: advanced-automation
        image: advanced-automation-v3.1:latest
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: advanced-automation-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: models
          mountPath: /app/models
      volumes:
      - name: logs
        emptyDir: {}
      - name: models
        emptyDir: {}
      restartPolicy: Always
