apiVersion: v1
kind: Namespace
metadata:
  name: manager-agent-ai-aws
  labels:
    name: manager-agent-ai-aws
    app: manager-agent-ai
    version: "2.9"
    cloud: "aws"
    ai-enhanced: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: manager-agent-ai-aws
data:
  AWS_REGION: "us-east-1"
  AWS_EKS_CLUSTER: "manager-agent-ai-eks"
  AWS_NAMESPACE: "manager-agent-ai-aws"
  AWS_VPC_ID: "vpc-12345678"
  AWS_SUBNET_IDS: "subnet-12345678,subnet-87654321"
  AWS_SECURITY_GROUP: "sg-12345678"
  AWS_LOAD_BALANCER: "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/manager-agent-ai/1234567890123456"
  AWS_CERTIFICATE_ARN: "arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"
  AWS_ROUTE53_HOSTED_ZONE: "Z1234567890ABC"
  AWS_S3_BUCKET: "manager-agent-ai-data"
  AWS_RDS_ENDPOINT: "manager-agent-ai.cluster-123456789012.us-east-1.rds.amazonaws.com"
  AWS_ELASTICACHE_ENDPOINT: "manager-agent-ai.123456789012.cache.amazonaws.com"
  AWS_SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/123456789012/manager-agent-ai-queue"
  AWS_SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:123456789012:manager-agent-ai-topic"
  AWS_LAMBDA_FUNCTION: "manager-agent-ai-lambda"
  AWS_SAGEMAKER_ENDPOINT: "manager-agent-ai-sagemaker"
  AWS_BEDROCK_MODEL: "anthropic.claude-3-sonnet-20240229-v1:0"
  AWS_COMPREHEND_ROLE: "arn:aws:iam::123456789012:role/ComprehendRole"
  AWS_REKOGNITION_COLLECTION: "manager-agent-ai-faces"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: manager-agent-ai-aws
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "QUtJQUlPU0ZPRE5OMEVYQU1QTEU="
  AWS_SECRET_ACCESS_KEY: "d0phbHJYVXRuRkVNSS9LN01ERU5HT0xYV1F3U2F3N0V5V2VrV2E="
  AWS_SESSION_TOKEN: "d0phbHJYVXRuRkVNSS9LN01ERU5HT0xYV1F3U2F3N0V5V2VrV2E="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ai-service
  namespace: manager-agent-ai-aws
  labels:
    app: aws-ai-service
    version: "2.9"
    cloud: "aws"
    ai-enhanced: "true"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: aws-ai-service
  template:
    metadata:
      labels:
        app: aws-ai-service
        version: "2.9"
        cloud: "aws"
        ai-enhanced: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: aws-ai-service-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: aws-ai-service
        image: manager-agent-ai/aws-ai-service:2.9.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: CLOUD_PROVIDER
          value: "aws"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: AWS_REGION
        - name: AWS_EKS_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: AWS_EKS_CLUSTER
        - name: AWS_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: AWS_NAMESPACE
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SESSION_TOKEN
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "4Gi"
            cpu: "4000m"
            ephemeral-storage: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
        - name: data
          mountPath: /app/data
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: aws-ai-service-pvc
      nodeSelector:
        kubernetes.io/os: linux
        node.kubernetes.io/instance-type: "m5.large"
        node.kubernetes.io/cloud-provider: "aws"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - aws-ai-service
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - "m5.large"
                - "m5.xlarge"
                - "m5.2xlarge"
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: aws-ai-service
  namespace: manager-agent-ai-aws
  labels:
    app: aws-ai-service
    version: "2.9"
    cloud: "aws"
    ai-enhanced: "true"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-redirect: "443:80"
spec:
  selector:
    app: aws-ai-service
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-ai-service-pvc
  namespace: manager-agent-ai-aws
  labels:
    app: aws-ai-service
    version: "2.9"
    cloud: "aws"
    ai-enhanced: "true"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ai-service-sa
  namespace: manager-agent-ai-aws
  labels:
    app: aws-ai-service
    version: "2.9"
    cloud: "aws"
    ai-enhanced: "true"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/manager-agent-ai-eks-role"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-ai-service-role
  namespace: manager-agent-ai-aws
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-ai-service-rolebinding
  namespace: manager-agent-ai-aws
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-ai-service-role
subjects:
- kind: ServiceAccount
  name: aws-ai-service-sa
  namespace: manager-agent-ai-aws
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aws-ai-service-hpa
  namespace: manager-agent-ai-aws
  labels:
    app: aws-ai-service
    version: "2.9"
    cloud: "aws"
    ai-enhanced: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws-ai-service
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aws-ai-service-pdb
  namespace: manager-agent-ai-aws
  labels:
    app: aws-ai-service
    version: "2.9"
    cloud: "aws"
    ai-enhanced: "true"
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: aws-ai-service
